<script setup lang="ts">
import {
  computed,
} from 'vue'

import {
  Line,
} from 'vue-chartjs'

import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Tooltip,
  Filler,
} from 'chart.js'

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Tooltip,
  Filler,
)

const {
  data,
} = await useFetch(
  '/api/dashboard',
)

const history =
  computed(
    () =>
      data.value?.history ?? [],
  )

const chartData =
  computed(() => ({
    labels:
      history.value
        .slice()
        .reverse()
        .map(
          (_, index) =>
            index + 1,
        ),

    datasets: [
      {
        data:
          history.value
            .slice()
            .reverse()
            .map(
              item =>
                Number(
                  item.totalProfit,
                ),
            ),

        fill: true,

        tension: 0.4,

        borderColor:
          '#00C389',

        backgroundColor:
          'rgba(0,195,137,0.08)',

        pointRadius: 0,
      },
    ],
  }))

const chartOptions = {
  responsive: true,

  maintainAspectRatio:
    false,

  plugins: {
    legend: {
      display: false,
    },
  },

  scales: {
    x: {
      display: false,
    },

    y: {
      ticks: {
        color:
          '#94A3B8',
      },

      grid: {
        color:
          'rgba(255,255,255,0.04)',
      },
    },
  },
}
</script>

<template>
  <section
    id="growth"
    class="
    reveal-section
      mx-auto

      max-w-7xl

      px-6
      py-32
    "
  >
    <div
      class="
        text-center
      "
    >
      <p
        class="
          text-sm
          font-semibold

          tracking-widest

          text-[#00C389]
        "
      >
        LIVE PERFORMANCE
      </p>

      <h2
        class="
          mt-4

          text-4xl
          font-bold

          md:text-6xl
        "
      >
        Profit Growth
      </h2>

      <p
        class="
          mx-auto

          mt-6

          max-w-3xl

          text-slate-400
        "
      >
        Real performance data
        generated by the
        Quetzal X arbitrage
        engine.
      </p>
    </div>

    <div
      class="
        mt-20

        rounded-3xl

        border
        border-slate-800

        bg-slate-900/70

        p-8

        backdrop-blur
      "
    >
      <div
        class="
          h-[400px]
        "
      >
        <Line
          :data="
            chartData
          "
          :options="
            chartOptions
          "
        />
      </div>
    </div>
  </section>
</template>